import 'package:dartz/dartz.dart';
import 'package:timebuddy/core/errors/failures.dart';
import 'package:timebuddy/features/locations/domain/entities/city_entity.dart';

/// Read-only access to the shipped city catalog.
///
/// The catalog is a static asset generated by `scripts/build_city_catalog.dart`
/// and never written at runtime, so there is no save path here. Both methods
/// are backed by the same in-memory parse: the first call reads the asset, the
/// rest are list walks (docs/specs/locations.md, Performance).
///
/// A broken asset must not take the app down: both methods answer
/// `Left(ServerFailure)` and only the add-location sheet shows the error. The
/// board keeps rendering from the labels it stored at add time.
///
/// ```dart
/// final result = await catalog.search('sao paulo');
/// result.fold(
///   (failure) => emit(const LocationSearchError()),
///   (cities) => emit(LocationSearchResults(cities: cities)),
/// );
/// ```
abstract class CityCatalogRepository {
  /// Loads and parses the asset. Idempotent and cached in memory.
  Future<Either<Failure, List<CityEntity>>> load();

  /// Ranked search over name, aliases, country and state.
  ///
  /// Ranking is exact match, then prefix, then substring, ties broken by
  /// descending `prominence` (docs/specs/locations.md rule 9). A raw IANA id
  /// also matches, so a pasted `Asia/Tokyo` does not dead-end (rule 10).
  /// Matching is accent- and case-insensitive via `normalizeForSearch`.
  ///
  /// An empty or whitespace-only [query] returns the curated default list, so
  /// the sheet is useful before anything is typed. At most [limit] results.
  Future<Either<Failure, List<CityEntity>>> search(
    String query, {
    int limit = 30,
  });
}
